### ISSUE TITLE
Activité Login

### ISSUE THREAD

**Issue by D0oM** [KraTuX31/Berbie_DeRoquemaurel_Gayout_ANDROID#20]
En tant qu'utilisateur je dois pouvoir renseigner mes identifiants et me connecter dans l'application

**Comment by KraTuX31** [comment]
ça serait bien qu'elle soit  : 
- **présente** au démarrage de l'application si aucun utilisateur dans la base
- **non présente** au démarrage si déjà préalablement renseigné

**Comment by aroquemaurel** [comment]
On avait pas dis que dans un premier temps, l'activité login, c'était factultatif ? Que la majorité des utilisateurs sont « non connecté », et que par contre, si tu veux prendre une photo, ça te demande juste un pseudal ?

**Comment by D0oM** [comment]
Si au final on reste bien entendu en local, mais vu que dans le menu qui était existant on avait un pseudo on peut dire que on l'a rajouté en prévoyant une version en ligne.
Pour le moment si on ne sélectionne rien le pseudo affiché c'est celui de base "userName", si par contre on le modifie on peut voir le pseudo choisi.
Après ça peut être une bonne idée de faire passer l'activité en première position si la personne n'a rien choisit voir même juste après qu'il ai pris la photo juste avant les tags.
A voir !
