### ISSUE TITLE
Le pseudo n'est pas mis a jour lors de l'affichage d'une photo

### ISSUE THREAD

**Issue by D0oM** [KraTuX31/Berbie_DeRoquemaurel_Gayout_ANDROID#52]

**Comment by D0oM** [comment]
Le problème viens du fait que le pseudo est récupéré dans la session lors de l'ajout du markeur, et que si on a l'activité login en première il faut qu'elle set l'user dans la session. 
Pour le moment c'est la mainActivity qui le faisait.

**Comment by aroquemaurel** [comment]
Oki doki ! 

Tu as commencé, ou tu veux que je m'en occupe ?

**Comment by D0oM** [comment]
C'est fait sur la branche 46, qui est a tester, sinon il suffit d'enlever le session.setUser dans la mainActivity et ça fonctionnera parfaitement

**Comment by D0oM** [comment]
Régler avec le merge 46
