### ISSUE TITLE
Prise de photo, mauvaise coordonnées GPS sur nexus

### ISSUE THREAD

**Issue by aroquemaurel** [KraTuX31/Berbie_DeRoquemaurel_Gayout_ANDROID#54]
Lorsque l'on prends une photo, les coordonnées GPS de la photo sont mises à 0.0, 0.0 sur la nexus.

**Comment by KraTuX31** [comment]
en fait c'est pas propre à la nexus je pense.
SI le GPS n'est pas activé, il te fait l'activé mais n'enregistre pas derrière les coordonnées GPS (je l'ai corrigé sur ma branche s'il s'agit bien de cela)
